# Generated by Django 3.2.5 on 2021-07-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=400)),
                ('pub_date', models.DateField()),
                ('pub_day', models.CharField(max_length=10)),
            ],
        ),
    ]
